import { WeatherInfo } from "./types";

export const weatherData: Record<string, WeatherInfo> = {
  London: {
    temperature: "15°C",
    humidity: "80%",
    windSpeed: "10 km/h",
    condition: "Cloudy",
    pressure: "1015 hPa",
    visibility: "10 km",
  },
  Paris: {
    temperature: "18°C",
    humidity: "70%",
    windSpeed: "12 km/h",
    condition: "Sunny",
    pressure: "1013 hPa",
    visibility: "12 km",
  },
  NewYork: {
    temperature: "20°C",
    humidity: "65%",
    windSpeed: "15 km/h",
    condition: "Partly Cloudy",
    pressure: "1017 hPa",
    visibility: "9 km",
  },
  Tokyo: {
    temperature: "22°C",
    humidity: "75%",
    windSpeed: "8 km/h",
    condition: "Rainy",
    pressure: "1012 hPa",
    visibility: "8 km",
  },
  Berlin: {
    temperature: "16°C",
    humidity: "78%",
    windSpeed: "10 km/h",
    condition: "Cloudy",
    pressure: "1016 hPa",
    visibility: "11 km",
  },
  Madrid: {
    temperature: "19°C",
    humidity: "68%",
    windSpeed: "11 km/h",
    condition: "Sunny",
    pressure: "1014 hPa",
    visibility: "10 km",
  },
  Rome: {
    temperature: "21°C",
    humidity: "72%",
    windSpeed: "9 km/h",
    condition: "Sunny",
    pressure: "1013 hPa",
    visibility: "12 km",
  },
  Beijing: {
    temperature: "25°C",
    humidity: "50%",
    windSpeed: "20 km/h",
    condition: "Sunny",
    pressure: "1009 hPa",
    visibility: "15 km",
  },
  Sydney: {
    temperature: "28°C",
    humidity: "60%",
    windSpeed: "18 km/h",
    condition: "Partly Cloudy",
    pressure: "1010 hPa",
    visibility: "14 km",
  },
  CapeTown: {
    temperature: "23°C",
    humidity: "55%",
    windSpeed: "22 km/h",
    condition: "Windy",
    pressure: "1008 hPa",
    visibility: "16 km",
  },
  Delhi: {
    temperature: "30°C",
    humidity: "40%",
    windSpeed: "10 km/h",
    condition: "Hazy",
    pressure: "1006 hPa",
    visibility: "7 km",
  },
  Lagos: {
    temperature: "29°C",
    humidity: "85%",
    windSpeed: "15 km/h",
    condition: "Rainy",
    pressure: "1005 hPa",
    visibility: "8 km",
  },
  Johannesburg: {
    temperature: "20°C",
    humidity: "65%",
    windSpeed: "12 km/h",
    condition: "Cloudy",
    pressure: "1012 hPa",
    visibility: "12 km",
  },
  Nairobi: {
    temperature: "25°C",
    humidity: "60%",
    windSpeed: "9 km/h",
    condition: "Sunny",
    pressure: "1010 hPa",
    visibility: "14 km",
  },
  Cairo: {
    temperature: "35°C",
    humidity: "20%",
    windSpeed: "25 km/h",
    condition: "Sunny",
    pressure: "1003 hPa",
    visibility: "20 km",
  },
  Moscow: {
    temperature: "10°C",
    humidity: "85%",
    windSpeed: "8 km/h",
    condition: "Snowy",
    pressure: "1018 hPa",
    visibility: "6 km",
  },
  Toronto: {
    temperature: "5°C",
    humidity: "80%",
    windSpeed: "10 km/h",
    condition: "Snowy",
    pressure: "1020 hPa",
    visibility: "4 km",
  },
  Miami: {
    temperature: "32°C",
    humidity: "75%",
    windSpeed: "10 km/h",
    condition: "Sunny",
    pressure: "1010 hPa",
    visibility: "15 km",
  },
  RioDeJaneiro: {
    temperature: "28°C",
    humidity: "70%",
    windSpeed: "15 km/h",
    condition: "Sunny",
    pressure: "1011 hPa",
    visibility: "14 km",
  },
  BuenosAires: {
    temperature: "22°C",
    humidity: "60%",
    windSpeed: "12 km/h",
    condition: "Cloudy",
    pressure: "1014 hPa",
    visibility: "10 km",
  },
  Santiago: {
    temperature: "20°C",
    humidity: "55%",
    windSpeed: "8 km/h",
    condition: "Sunny",
    pressure: "1015 hPa",
    visibility: "13 km",
  },
  Bangkok: {
    temperature: "34°C",
    humidity: "75%",
    windSpeed: "10 km/h",
    condition: "Humid",
    pressure: "1007 hPa",
    visibility: "9 km",
  },
  Dubai: {
    temperature: "40°C",
    humidity: "15%",
    windSpeed: "20 km/h",
    condition: "Hot",
    pressure: "1002 hPa",
    visibility: "20 km",
  },
  Singapore: {
    temperature: "31°C",
    humidity: "85%",
    windSpeed: "12 km/h",
    condition: "Rainy",
    pressure: "1005 hPa",
    visibility: "9 km",
  },
  KualaLumpur: {
    temperature: "30°C",
    humidity: "80%",
    windSpeed: "10 km/h",
    condition: "Rainy",
    pressure: "1006 hPa",
    visibility: "8 km",
  },
  Manila: {
    temperature: "33°C",
    humidity: "80%",
    windSpeed: "15 km/h",
    condition: "Humid",
    pressure: "1004 hPa",
    visibility: "10 km",
  },
  Karachi: {
    temperature: "38°C",
    humidity: "25%",
    windSpeed: "18 km/h",
    condition: "Hot",
    pressure: "1003 hPa",
    visibility: "18 km",
  },
  Seoul: {
    temperature: "12°C",
    humidity: "60%",
    windSpeed: "15 km/h",
    condition: "Cloudy",
    pressure: "1013 hPa",
    visibility: "11 km",
  },
  Islamabad: {
    temperature: "28°C",
    humidity: "40%",
    windSpeed: "12 km/h",
    condition: "Clear",
    pressure: "1012 hPa",
    visibility: "14 km",
  },
  Vienna: {
    temperature: "14°C",
    humidity: "70%",
    windSpeed: "10 km/h",
    condition: "Cloudy",
    pressure: "1015 hPa",
    visibility: "10 km",
  },
  Amsterdam: {
    temperature: "13°C",
    humidity: "75%",
    windSpeed: "12 km/h",
    condition: "Cloudy",
    pressure: "1014 hPa",
    visibility: "11 km",
  },
  Zurich: {
    temperature: "12°C",
    humidity: "80%",
    windSpeed: "10 km/h",
    condition: "Cloudy",
    pressure: "1017 hPa",
    visibility: "9 km",
  },
  Oslo: {
    temperature: "6°C",
    humidity: "85%",
    windSpeed: "8 km/h",
    condition: "Snowy",
    pressure: "1021 hPa",
    visibility: "5 km",
  },
  Reykjavik: {
    temperature: "3°C",
    humidity: "90%",
    windSpeed: "7 km/h",
    condition: "Snowy",
    pressure: "1023 hPa",
    visibility: "4 km",
  },
  Helsinki: {
    temperature: "5°C",
    humidity: "85%",
    windSpeed: "9 km/h",
    condition: "Snowy",
    pressure: "1020 hPa",
    visibility: "6 km",
  },
  Stockholm: {
    temperature: "7°C",
    humidity: "80%",
    windSpeed: "8 km/h",
    condition: "Cloudy",
    pressure: "1018 hPa",
    visibility: "8 km",
  },
  Dublin: {
    temperature: "11°C",
    humidity: "80%",
    windSpeed: "12 km/h",
    condition: "Rainy",
    pressure: "1015 hPa",
    visibility: "10 km",
  },
  Edinburgh: {
    temperature: "10°C",
    humidity: "82%",
    windSpeed: "11 km/h",
    condition: "Rainy",
    pressure: "1016 hPa",
    visibility: "9 km",
  },
};
